// Free, rule-based stand-in for the real Claude classifier — used in demo mode
// so the platform can be exercised end-to-end with no API key and no cost.
// Swap DEMO_MODE off (see claudeService.js) once a real ANTHROPIC_API_KEY is set.

// Deliberately specific phrases, not the bare word "budget" — otherwise
// "not sure on budget yet" would count as a signal instead of its opposite.
const BUDGET_SIGNALS = ['approved budget', 'have budget', 'budget approved', 'budget of', '$', 'per month', 'monthly budget', 'ready to spend', 'can afford', 'purchase', 'buy now'];
const TIMELINE_SIGNALS = ['asap', 'urgent', 'this week', 'this month', 'this quarter', 'immediately', 'right away', 'q1', 'q2', 'q3', 'q4', 'soon as possible'];
const DECIDER_SIGNALS = ['founder', 'owner', 'ceo', "i'm the", 'i am the', 'decision maker', 'director', 'vp ', 'head of', 'i run'];

function mockClassifyLead(customer, leadMessage) {
  const text = leadMessage.toLowerCase();

  const hasBudget = BUDGET_SIGNALS.some((s) => text.includes(s));
  const hasTimeline = TIMELINE_SIGNALS.some((s) => text.includes(s));
  const hasDecider = DECIDER_SIGNALS.some((s) => text.includes(s));
  const signalCount = [hasBudget, hasTimeline, hasDecider].filter(Boolean).length;

  let classification;
  let confidence;
  if (signalCount >= 2) {
    classification = 'hot';
    confidence = 80 + signalCount * 5;
  } else if (signalCount === 1) {
    classification = 'warm';
    confidence = 55;
  } else {
    classification = 'cold';
    confidence = 30;
  }

  const nextQuestion = (customer.qualifyingQuestions && customer.qualifyingQuestions[0]) ||
    "What's your timeline for making a decision?";

  return {
    classification,
    confidence: Math.min(confidence, 95),
    company_name: 'Not extracted (demo mode)',
    problem: leadMessage.slice(0, 160),
    budget: hasBudget ? 'Budget signal detected in message' : 'No budget signal detected',
    response_text: `Thanks for reaching out! ${nextQuestion} [Demo mode — this reply is rule-based, not generated by Claude.]`,
  };
}

module.exports = { mockClassifyLead };
