// Free, rule-based stand-in for the real Claude classifier — used in demo mode
// so the platform can be exercised end-to-end with no API key and no cost.
// Swap DEMO_MODE off (see claudeService.js) once a real ANTHROPIC_API_KEY is set.

// Deliberately specific phrases, not the bare word "budget" — otherwise
// "not sure on budget yet" would count as a signal instead of its opposite.
const BUDGET_SIGNALS = ['approved budget', 'have budget', 'budget approved', 'budget of', '$', 'per month', 'monthly budget', 'ready to spend', 'can afford', 'purchase', 'buy now'];
const TIMELINE_SIGNALS = ['asap', 'urgent', 'this week', 'this month', 'this quarter', 'immediately', 'right away', 'q1', 'q2', 'q3', 'q4', 'soon as possible'];
const DECIDER_SIGNALS = ['founder', 'owner', 'ceo', "i'm the", 'i am the', 'decision maker', 'director', 'vp ', 'head of', 'i run'];
// Genuine interest with no budget/timeline signal is still WARM (per the CSV's own
// classification criteria), not COLD — COLD is reserved for no real interest at all.
const INTEREST_SIGNALS = ['interested', 'tell me more', 'learn more', 'sounds good', 'want to', 'looking for', 'looking to', 'need help', 'schedule a call', 'demo', 'more info', 'sign up', 'get started'];

function mockClassifyLead(customer, leadMessage) {
  const text = leadMessage.toLowerCase();

  const hasBudget = BUDGET_SIGNALS.some((s) => text.includes(s));
  const hasTimeline = TIMELINE_SIGNALS.some((s) => text.includes(s));
  const hasDecider = DECIDER_SIGNALS.some((s) => text.includes(s));
  const hasInterest = INTEREST_SIGNALS.some((s) => text.includes(s));
  const signalCount = [hasBudget, hasTimeline, hasDecider].filter(Boolean).length;

  let classification;
  let confidence;
  if (signalCount >= 2) {
    classification = 'hot';
    confidence = 80 + signalCount * 5;
  } else if (signalCount === 1 || hasInterest) {
    classification = 'warm';
    confidence = 55;
  } else {
    classification = 'cold';
    confidence = 30;
  }

  const nextQuestion = (customer.qualifyingQuestions && customer.qualifyingQuestions[0]) ||
    "What's your timeline for making a decision?";

  return {
    classification,
    confidence: Math.min(confidence, 95),
    company_name: 'Not extracted (demo mode)',
    problem: leadMessage.slice(0, 160),
    budget: hasBudget ? 'Budget signal detected in message' : 'No budget signal detected',
    response_text: `Thanks for reaching out! ${nextQuestion} [Demo mode — this reply is rule-based, not generated by Claude.]`,
  };
}

// Free, rule-based stand-in for Claude's agent-config drafting, used in demo mode.
function mockDraftAgentConfig(description) {
  const text = String(description || '').toLowerCase();
  const mentionsEnterprise = /enterprise|corporate|large company/.test(text);
  const mentionsSmall = /small|local|solo|freelance|startup/.test(text);

  return {
    icp_size: mentionsEnterprise ? '200+ employees' : mentionsSmall ? '1-20 employees' : '20-100 employees',
    icp_budget: mentionsEnterprise ? '$100k+ annual budget' : mentionsSmall ? '$5k-$25k annual budget' : '$25k-$100k annual budget',
    qualifying_questions: [
      'What problem are you trying to solve, and how are you handling it today?',
      "What's your timeline for making a decision?",
      'Who else is involved in this decision?',
      '[Demo mode — these questions are generic, not generated by Claude.]',
    ],
  };
}

module.exports = { mockClassifyLead, mockDraftAgentConfig };
