// Real digital marketing agencies matching LeadQualify AI's ICP (5-25 people,
// full-service/SEO/PPC agencies). Every entry below was independently verified
// on 2026-07-29 by fetching the company's own website directly (not just taking
// a directory's word for it) — see `source` and `verifiedAt` on each entry.
// Team sizes are approximate; agencies rarely publish an exact headcount.
//
// This is the fallback dataset scripts/find-prospects.js starts from. It's real,
// not filler — the live-search path (see find-prospects.js) only ADDS to this,
// it never replaces it.

const SEED_PROSPECTS = [
  {
    name: 'Incrementors',
    website: 'https://incrementors.com/',
    city: 'Sacramento, CA',
    teamSizeNote: '~14 employees (best ICP fit in this seed set)',
    specialty: 'SEO, PPC, web design, lead generation',
    phone: '+1 (916) 273-6673',
    email: null,
    source: 'OneLittleWeb directory listing (14 employees) + direct site verification',
    verifiedAt: '2026-07-29',
  },
  {
    name: 'Volume Nine',
    website: 'https://v9digital.com/',
    city: 'Denver, CO',
    teamSizeNote: '10-49 employees (Clutch-verified bucket)',
    specialty: 'SEO, content optimization, social media, GEO',
    phone: '(303) 955-5228',
    email: null,
    source: 'Clutch.co directory listing + direct site verification',
    verifiedAt: '2026-07-29',
  },
  {
    name: 'SimpleTiger',
    website: 'https://www.simpletiger.com/',
    city: 'Sarasota, FL',
    teamSizeNote: '10-49 employees (Clutch-verified bucket)',
    specialty: 'B2B SaaS SEO, paid ads, content marketing',
    phone: '+1 (941) 893-4118',
    email: null,
    source: 'Clutch.co directory listing (4.9/5, 31 reviews) + direct site verification',
    verifiedAt: '2026-07-29',
  },
  {
    name: 'Searchbloom',
    website: 'https://www.searchbloom.com/',
    city: 'South Jordan, UT',
    teamSizeNote: 'Not disclosed; boutique SEO/PPC shop',
    specialty: 'SEO, PPC, CRO, digital analytics',
    phone: '801.590.4051',
    email: 'hello@searchbloom.com',
    source: 'Directory listing + direct site verification',
    verifiedAt: '2026-07-29',
  },
  {
    name: 'Funnel Boost Media',
    website: 'https://funnelboostmedia.net/',
    city: 'San Antonio, TX',
    teamSizeNote: 'Not disclosed; operating since 2012',
    specialty: 'Local SEO, national SEO, PPC, lead generation',
    phone: '(210) 757-3522',
    email: null,
    source: 'MarketingLTB directory listing + direct site verification',
    verifiedAt: '2026-07-29',
  },
  {
    name: 'ForeFront Web',
    website: 'https://www.forefrontweb.com/',
    city: 'Dublin, OH',
    teamSizeNote: 'Not disclosed; boutique web + SEO shop',
    specialty: 'SEO, web design, PPC, content marketing',
    phone: '614.886.4000',
    email: 'info@forefrontweb.com',
    source: 'MarketingLTB directory listing + direct site verification',
    verifiedAt: '2026-07-29',
  },
  {
    name: 'Sticky Digital',
    website: 'https://stickydigital.io/',
    city: 'Not disclosed (North America)',
    teamSizeNote: '11-50 employees (per MarketingLTB)',
    specialty: 'Retention marketing (email/SMS) for DTC/Shopify brands',
    phone: null,
    email: 'nikki@stickydigital.io',
    source: 'MarketingLTB directory listing + direct site verification',
    verifiedAt: '2026-07-29',
  },
  {
    name: 'Set Fire Creative',
    website: 'https://setfirecreative.com/',
    city: 'Orem, UT',
    teamSizeNote: 'Not disclosed; "99% employee retention" cited',
    specialty: 'Paid/organic social, PPC, SEO, landing pages',
    phone: '(385) 250-3081',
    email: null,
    source: 'MarketingLTB directory listing + direct site verification',
    verifiedAt: '2026-07-29',
  },
  {
    name: 'Taktical Digital',
    website: 'https://taktical.co/',
    city: 'New York, NY',
    teamSizeNote: 'Not disclosed; "150+ partners" network cited',
    specialty: 'Paid social, paid search, SEO/content, creator content',
    phone: null,
    email: null,
    source: 'MarketingLTB directory listing + direct site verification',
    verifiedAt: '2026-07-29',
  },
  {
    name: 'BlueTuskr',
    website: 'https://www.bluetuskr.com/',
    city: 'West Chester, PA',
    teamSizeNote: '"30+ in-house experts" — slightly above the 5-25 ICP ceiling, kept as an adjacent/growth-tier prospect',
    specialty: 'Ecommerce marketing: paid media, content, marketplace management',
    phone: null,
    email: null,
    source: 'Clutch.co directory listing + direct site verification',
    verifiedAt: '2026-07-29',
  },
];

module.exports = { SEED_PROSPECTS };
